version: "2.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    container_name: ros2robotik
    working_dir: /linefollower
    volumes:
      - .:/linefollower
      - /tmp/argus_socket:/tmp/argus_socket
    ports:
      - "8888:8888/udp"
      - "80:80"
    stdin_open: true
    tty: true