version: "2.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    container_name: ros2robotik
    working_dir: /linefollower
    volumes:
      - .:/linefollower
      - /tmp/argus_socket:/tmp/argus_socket
    ports:
      - "8888:8888/udp"
      - "80:80"
    command: bash -c "ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888 &&
                     python LineFollower.py"
    stdin_open: true
    tty: true